### ISSUE TITLE
How decode token in getGoogleCerts?

### ISSUE THREAD

**Issue by pansardinicolas** [jmreyes/passport-google-id-token#18]
Hi.
How may I decode a 64 bit auth credential received in a HTTP header?
I thought about adding a function to the getGoogleCerts, but your usage documentation is not well explained. How would I do that? Is there any parameter available?

**Comment by jmreyes** [comment]
Hi, not sure I get what you're trying to achieve, but in order to define a custom `getGoogleCerts` you just need to implement a function in the same form as [the one provided by default](https://github.com/jmreyes/passport-google-id-token/blob/master/lib/passport-google-id-token/strategy.js#L69) and place it inside the options [as indicated in the documentation](https://github.com/jmreyes/passport-google-id-token#configure-strategy).

About the HTTP header, you can get the ID token from there if you use `id_token` as key ([relevant commit](https://github.com/jmreyes/passport-google-id-token/commit/ce55db3400bc860affcb8f633dcb203141fba505)).

**Comment by pansardinicolas** [comment]
My id_token is 64 bit encoded and it seems not possible to decode inside the strategy, as the server has returned 401 before get in the scope of the strategy.

**Comment by jmreyes** [comment]
You could add another middleware just before `passport-google-id-token` with your decoding logic, that sets e.g. `req.body.id_token` to the value this strategy is expecting (maybe also check the [different options](https://github.com/jmreyes/passport-google-id-token/blob/master/lib/passport-google-id-token/strategy.js#L101) you have and leave only one on the request object). It would go somehow like this:
```javascript
app.post('/auth/google',
  function (req, res, next) {
    decoded_token = // Get your token from req and decode it
    req.body.id_token = decoded_token;
    next();
  },
  passport.authenticate('google-id-token'),
  function (req, res) {
    // do something with req.user
    res.send(req.user? 200 : 401);
  }
);
```

**Comment by pansardinicolas** [comment]
Thanks, it works with Postman. 
BTW my node api returns 400 when the request comes from Android app, I looked up the header and they are the same.
Is there any other validation in the passport for android clients?

**Comment by jmreyes** [comment]
No, there is no client-specific handling, the problem is most probably on your end...
You're welcome!

**Comment by pansardinicolas** [comment]
Well as it may help you, I printed out my errors and found out there were 2 problems.

- Passport authentication calls both serializeUser and deserializeUser and they won't work if their parameters were anything different but User (was using User.id).

- Inside the [route](https://github.com/jmreyes/passport-google-id-token#authenticate-requests) to authenticate the request "req.user" may not be printed after deserialize, I've got typeError and cyclic structures when trying to JSON.stringify.

After fixing them, it returns 200 and works as a charm.
