### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by remirobert** [jmreyes/passport-google-id-token#7]
Hello,

I used your module to authenticate my user from mobile. So I got the access token throw the google SDK, in the mobile side. I sent it to my API throw a POST request with the argument access_token.

I got an error in your module here: 
```Javascript
var decodedToken = jwt.decode(idToken, {complete: true, json: true});
```

I checked the idToken is well filled with my token passed throw the http POST request.

For the passport strategy, I just provide the google ID: 
```Javascript
passport.use(new GoogleTokenStrategy({
    clientID: configAuth.google.appID
  },...
```

Thanks in advance for your help.

**Comment by jmreyes** [comment]
Hi! What kind of error are you getting? That line should call [this method](https://github.com/auth0/node-jsonwebtoken/blob/master/index.js#L12) from the `jsonwebtoken` module. You could also try to decode the token using e.g. https://jwt.io/ and tell me about its structure, so that I can try to replicate the problem. Thanks!

**Comment by remirobert** [comment]
It's okay ! In fact my access_token wasn't the good one. It works fine, with the good one.
Thanks :+1:
